[package]
name = "cshell-ssh"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["ssh-russh"]
ssh-russh = []
legacy-crypto = ["russh/des", "russh/dsa"]
x11-forwarding = []

[dependencies]
russh.workspace = true
serde.workspace = true
thiserror.workspace = true
tokio.workspace = true

[dev-dependencies]
rand.workspace = true

[lints]
workspace = true
