[package]
name = "cshell-terminal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[features]
default = ["alacritty-adapter"]
alacritty-adapter = []
probe-terminal = []

[dependencies]
alacritty_terminal.workspace = true
cshell-domain = { path = "../cshell-domain" }
serde.workspace = true
thiserror.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
